// <auto-generated />
namespace ToDoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userrole));
        
        string IMigrationMetadata.Id
        {
            get { return "202006191443126_userrole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
